---
version: "2"
volumes:
  mpd-data: null
  fifo: null
  mpd-default-data: null
  mpd-default-kitchen-data: null
  mpd-default-hall-data: null
  radio-data: null
  pifi-data: null
  mpdfm-data: null
  snapserver-data: null
  snapchanger-data: null
  snapcron-data: null
  shairportsync-main: null
  plexamp-data: null
  mopidy-data: null
  music-shares-data: null
  upmpdcli-data: null
services:
  mpd-radio:
    image: registry.local:5000/mpd
    build:
      context: ./mpd
    volumes:
      - fifo:/fifo/
      - mpd-data:/etc/mpd.conf
    ports:
      - 36602:6600
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  mpd-default:
    image: registry.local:5000/mpd
    build:
      context: ./mpd
    volumes:
      - fifo:/fifo/
      - mpd-default-data:/etc/mpd.conf
    ports:
      - 6600:6600
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  mpd-room:
    image: registry.local:5000/mpd
    build:
      context: ./mpd
    volumes:
      - fifo:/fifo/
      - mpd-data:/etc/mpd.conf
    ports:
      - 6602:6600
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  mpd-zal:
    image: registry.local:5000/mpd
    build:
      context: ./mpd
    volumes:
      - fifo:/fifo/
      - mpd-data:/etc/mpd.conf
    ports:
      - 6601:6600
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  mpd-kitchen:
    image: registry.local:5000/mpd
    build:
      context: ./mpd
    volumes:
      - fifo:/fifo/
      - mpd-default-kitchen-data:/etc/mpd.conf
    ports:
      - 6603:6600
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  mpd-hall:
    image: registry.local:5000/mpd
    build:
      context: ./mpd
    volumes:
      - fifo:/fifo/
      - mpd-default-hall-data:/etc/mpd.conf
    ports:
      - 6604:6600
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  radio:
    image: registry.local:5000/radio
    build:
      context: ./radio
    volumes:
      - radio-data:/root/radio_supervisor.py
      - radio-data:/root/radio_supervisor2.py
      - radio-data:/root/radio_supervisor2.sh
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  pifi:
    image: registry.local:5000/pifi
    build:
      context: ./pifi.radio
    depends_on:
      - radio
    ports:
      - 3000
    volumes:
      - pifi-data:/etc/pifi/streams.json
      - pifi-data:/etc/pifi/config.json
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  mpdfm:
    image: registry.local:5000/mpdfm
    build:
      context: ./mpd.fm
    depends_on:
      - radio
    environment:
      - MPD_HOST=mpd-radio
      - MPD_PORT=6600
      - PORT=4200
      - STATION_FILE=/app/stations.json
    ports:
      - 4200
    volumes:
      - mpdfm-data:/app/stations.json
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  snapserver:
    image: registry.local:5000/snapserver
    build:
      context: ./snapserver
    network_mode: host
    ports:
      - 1704:1704
      - 1705:1705
    environment:
      - SERVICE_NAME=Snapcast
      - SERVICE_PORT=1704
      - SERVICE_TYPE=_snapcast._tcp
    volumes:
      - fifo:/fifo/
      - snapserver-data:/etc/snapserver.conf
    restart: unless-stopped
  snapcastr:
    image: registry.local:5000/snapcastr
    build:
      context: ./snapcastr
    depends_on:
      - snapserver
    ports:
      - 5011:5011
    environment:
      - SNAPCAST_HOST=${SNAPCAST_HOST}
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  snapchanger:
    image: registry.local:5000/snapchanger
    build:
      context: ./snapchanger
    depends_on:
      - snapserver
    environment:
      - SNAPCAST_HOST=${SNAPCAST_HOST}
    volumes:
      - snapchanger-data:/root/snapchanger.py
      - snapchanger-data:/root/snapchanger.sh
    networks:
      - snapcast
    restart: unless-stopped
  snapcron:
    image: registry.local:5000/snapcron
    build:
      context: ./snapcron
    depends_on:
      - snapserver
    environment:
      - SNAPCAST_HOST=${SNAPCAST_HOST}
    networks:
      - snapcast
    volumes:
      - snapcron-data:/etc/crontabs/root
      - snapcron-data:/scripts
    restart: unless-stopped
  shairportSync-main:
    restart: always
    image: kevineye/shairport-sync
    network_mode: host
    environment:
      - AIRPLAY_NAME=Multiroom
    volumes:
      - fifo:/fifo
      - shairportsync-main:/etc/localtime:ro
    command:
      - -p
      - "5001"
      - -o
      - pipe
      - --
      - /fifo/snapfifo.shairport
  plexamp:
    network_mode: host
    image: registry.local:5000/plexamp
    build:
      context: ./plexamp
    ports:
      - 20000:20000
    environment:
      - TZ=Europe/Berlin
    volumes:
      - fifo:/fifo/
      - plexamp-data:/root/.config/Plexamp
      - plexamp-data:/etc/mpd.conf
    restart: unless-stopped
  mopidy:
    image: whhoesj/mopidy
    ports:
      - 6680:6680
      - 6681:6681
      - 16600:6600
    volumes:
      - fifo:/fifo/
      - mopidy-data:/var/lib/mopidy
      - music-shares-data:/media:ro
      - mopidy-data:/etc/mopidy.conf
    networks:
      - snapcast
      - proxy-local
    restart: unless-stopped
  upmpdcli:
    image: registry.local:5000/upmpdcli
    build:
      context: ./upmpdcli
    network_mode: host
    environment:
      - TZ=America/Guayaquil
    volumes:
      - fifo:/fifo/
      - upmpdcli-data:/etc/mpd.conf
    restart: unless-stopped
networks:
  proxy-local:
    external: true
  snapcast: null

